# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0003_pista_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pista',
            name='id',
        ),
        migrations.AddField(
            model_name='pista',
            name='color',
            field=models.CharField(choices=[('VERDE', 'Verde'), ('AZUL', 'Azul'), ('MARRON', 'Marrón')], default='AZUL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pista',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pista',
            name='tipo_pared',
            field=models.CharField(choices=[('CEMENTO', 'Cemento'), ('METACRILATO', 'Metacrilato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pista',
            name='tipo_superficie',
            field=models.CharField(choices=[('CESPED', 'Césped artificial'), ('HORMIGON', 'Hormigón poroso'), ('MOQUETA', 'Moqueta')], max_length=20),
        ),
    ]
