# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easypadel', '0005_auto_20170220_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Foto de perfil')),
                ('foto_cabecera', models.ImageField(blank=True, null=True, upload_to='header_pics/%Y-%m-%d/', verbose_name='Foto de cabecera')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener el siguiente formato: '+999999999'. Permitidos hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
    ]
