# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0010_auto_20170301_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='email',
        ),
    ]
