# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0015_remove_pista_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easypadel.Empresa'),
            preserve_default=False,
        ),
    ]
