# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0016_pista_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/pista_img/empresa/nombre/', verbose_name='Foto de pista'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='foto_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/cabecera_img/%Y-%m-%d/', verbose_name='Foto de cabecera'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/perfil_img/%Y-%m-%d/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='foto_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/cabecera_img/%Y-%m-%d/', verbose_name='Foto de cabecera'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/perfil_img/%Y-%m-%d/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/cabecera_img/%Y-%m-%d/', verbose_name='Foto de cabecera'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/perfil_img/%Y-%m-%d/', verbose_name='Foto de perfil'),
        ),
    ]
