# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0018_auto_20170307_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/pistas/', verbose_name='Foto de pista'),
        ),
    ]
