# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0020_auto_20170308_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='pista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/pistas/%Y-%m-%d/', verbose_name='Foto de pista'),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Horario'),
        ),
    ]
