# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0021_auto_20170310_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franjahoraria',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
