# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0022_auto_20170314_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='pistas',
            field=models.ManyToManyField(to='easypadel.Pista'),
        ),
    ]
