# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0023_horario_pistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAsignacionHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='horario',
            name='pistas',
        ),
        migrations.AddField(
            model_name='diaasignacionhorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Horario'),
        ),
        migrations.AddField(
            model_name='diaasignacionhorario',
            name='pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Pista'),
        ),
    ]
