# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0024_auto_20170320_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaasignacionhorario',
            name='dia',
            field=models.DateField(verbose_name='Día'),
        ),
    ]
