# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0026_auto_20170321_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAsignacionHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Día')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Horario')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Pista')),
            ],
        ),
    ]
