# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0027_diaasignacionhorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaasignacionhorario',
            name='horario',
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='asignada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franjahoraria',
            name='dia_asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypadel.DiaAsignacionHorario'),
        ),
    ]
