# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0028_auto_20170322_1206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diaasignacionhorario',
            unique_together=set([('pista', 'dia')]),
        ),
    ]
