# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0029_auto_20170327_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pista',
            name='color',
        ),
    ]
