# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0032_auto_20170330_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='franjahoraria',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easypadel.Jugador'),
        ),
    ]
