# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0033_franjahoraria_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='foto_cabecera',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='foto_cabecera',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='foto_cabecera',
        ),
    ]
