# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0034_auto_20170419_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='foto_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/cabecera_img/%Y-%m-%d/', verbose_name='Foto de cabecera'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='foto_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/cabecera_img/%Y-%m-%d/', verbose_name='Foto de cabecera'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/cabecera_img/%Y-%m-%d/', verbose_name='Foto de cabecera'),
        ),
    ]
