# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0036_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(max_length=200),
        ),
    ]
