# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0037_auto_20170420_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics/%Y-%m-%d/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
