# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0039_auto_20170421_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('fecha_limite', models.DateTimeField()),
                ('fecha_partido', models.DateTimeField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], max_length=9)),
                ('tipo_partido', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('MIXTO', 'Mixto')], max_length=9)),
                ('sitio', models.CharField(blank=True, max_length=20, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='easypadel.Jugador')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Propuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together=set([('jugador', 'propuesta')]),
        ),
    ]
