# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0040_auto_20170426_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
