# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0042_auto_20170501_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='estado',
        ),
    ]
