# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0043_remove_propuesta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Propuesta'),
        ),
    ]
