# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0044_auto_20170501_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easypadel.Post')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Propuesta')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
            bases=('easypadel.post',),
        ),
    ]
