# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easypadel', '0045_comentario'),
    ]

    operations = [


        migrations.AddField(
            model_name='comentario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
