# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0048_auto_20170502_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='comentario_pics/%Y-%m-%d/', verbose_name='Foto')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Jugador')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.Propuesta')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
