# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0051_auto_20170511_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionempresa',
            name='empresa',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='easypadel.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoracionjugador',
            name='jugador',
            field=models.ForeignKey(default=77, on_delete=django.db.models.deletion.CASCADE, to='easypadel.Jugador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoracionpista',
            name='pista',
            field=models.ForeignKey(default=88, on_delete=django.db.models.deletion.CASCADE, to='easypadel.Pista'),
            preserve_default=False,
        ),
    ]
