# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0054_valoracion_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
