# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0056_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='franja_horaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easypadel.FranjaHoraria'),
            preserve_default=False,
        ),
    ]
