# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0057_resultado_franja_horaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='franja_horaria',
        ),
    ]
