# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypadel', '0059_resultado_franja_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='partidos_ganados',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='partidos_jugados',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='rating_victorias',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
